spring:
  datasource:
      url: jdbc:mysql://localhost:3306/board
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: 'false'
    generate-ddl: 'false'
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
        ddl-auto: create
    show-sql: 'true'




