spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/job-gsm?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    password: '123456'
  jpa:
    open-in-view: 'false'
    generate-ddl: 'false'
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: none
