spring:
  mvc:
    hidden-method:
      filter:
        enabled: 'true'
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/job-gsm?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    password: '123456'
  jpa:
    open-in-view: 'false'
    generate-ddl: 'false'
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: jobGSM2023@gmail.com
    password: yvxcaenfpjfdffkw
    port: '587'
  redis:
    host: 127.0.0.1
    port: '6379'


  main.allow-bean-definition-overriding: true
jwt:
  accessSecret: yOeHjKegnwjbli5csZbO1jE9r+qoGkpWgX2JdHjw3tI=
  refreshSecret: gjX7hf+563vQH/SMDh+K+A3MAbICvd3MtPLk/sZwizw=(